// flow-typed signature: 2d6f38f081dfb6e0156c0e17c626f9b2
// flow-typed version: <<STUB>>/docopt_v^0.6.2/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'docopt'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'docopt' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'docopt/docopt' {
  declare module.exports: any;
}

// Filename aliases
declare module 'docopt/docopt.js' {
  declare module.exports: $Exports<'docopt/docopt'>;
}
