// flow-typed signature: 5d93adbc8b781116a6c5fa5d5f4d4f70
// flow-typed version: <<STUB>>/passport-discord_v^0.1.3/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'passport-discord'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'passport-discord' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'passport-discord/example/server' {
  declare module.exports: any;
}

declare module 'passport-discord/lib/index' {
  declare module.exports: any;
}

declare module 'passport-discord/lib/strategy' {
  declare module.exports: any;
}

// Filename aliases
declare module 'passport-discord/example/server.js' {
  declare module.exports: $Exports<'passport-discord/example/server'>;
}
declare module 'passport-discord/lib/index.js' {
  declare module.exports: $Exports<'passport-discord/lib/index'>;
}
declare module 'passport-discord/lib/strategy.js' {
  declare module.exports: $Exports<'passport-discord/lib/strategy'>;
}
